app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'auth'), function () {
	Route::get('/', array( 'as' => 'admin.home', 'uses' => 'HomeController@index' ));

	// Artist
	Route::model('artist', 'Artist');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );
	Route::resource('artist', 'ArtistController');

	// ArtistMeta
	Route::model('artist-meta', 'ArtistMeta');
	Route::get( '/artist-setting/musicbrainz/{artist}/lookup', array( 'as' => 'artist-setting.musicbrainz.lookup', 'uses' => 'ArtistMetaController@lookup_musicbrainz' ) );
	Route::get( '/artist-setting/discogs/{artist}/lookup', array( 'as' => 'artist-setting.discogs.lookup', 'uses' => 'ArtistMetaController@lookup_discogs' ) );
	Route::get( '/artist-setting/itunes/{artist}/lookup', array( 'as' => 'artist-setting.itunes.lookup', 'uses' => 'ArtistMetaController@lookup_itunes' ) );
	Route::post( '/artist-setting/discogs/search', array( 'as' => 'artist-setting.discogs.search', 'uses' => 'ArtistMetaController@search_discogs' ) );
	Route::post( '/artist-setting/itunes/{artist}/search', array( 'as' => 'artist-setting.itunes.serach', 'uses' => 'ArtistMetaController@search_itunes' ) );
	Route::resource('artist-setting', 'ArtistMetaController');

	// ArtistMusicbrainz
	Route::post( '/artist-musicbrainz/search', array( 'as' => 'artist-musicbrainz.search', 'uses' => 'ArtistMusicbrainzController@index' ) );
	Route::resource( 'artist-musicbrainz', 'ArtistMusicbrainzController' );

	// ArtistItunes
	Route::post( '/artist-itunes/search', array( 'as' => 'artist-itunes.search', 'uses' => 'ArtistItunesController@index' ) );
	Route::resource( 'artist-itunes', 'ArtistItunesController' );

	// ArtistItunes
	Route::post( '/artist-discogs/search', array( 'as' => 'artist-discogs.search', 'uses' => 'ArtistDiscogsController@index' ) );
	Route::resource( 'artist-discogs', 'ArtistDiscogsController' );

	// AmazonSearch
	Route::post( '/amazon/search', array( 'as' => 'amazon.search', 'uses' => 'AmazonSearchController@index' ) );
	Route::resource( 'amazon', 'AmazonSearchController' );

	// Personnel
	Route::model('personnel', 'Personnel');
	Route::get( '/personnel/{personnel}/delete', array( 'as' => 'personnel.delete', 'uses' => 'PersonnelController@delete' ) );
	Route::post( '/personnel/save-order', array( 'as' => 'personnel.save-order', 'before' => 'csrf', 'uses' => 'PersonnelController@save_order' ) );
	Route::resource('personnel', 'PersonnelController');

	// Album
	Route::model('album', 'Album');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::resource('album', 'AlbumController');

	// AlbumMeta
	Route::model('album-meta', 'AlbumMeta');
	Route::get( '/album-setting/musicbrainz/{album}/lookup', array( 'as' => 'album-setting.musicbrainz.lookup', 'uses' => 'AlbumController@lookup_musicbrainz' ) );
	Route::get( '/album-setting/discogs/{album}/lookup', array( 'as' => 'album-setting.discogs.lookup', 'uses' => 'AlbumController@lookup_discogs' ) );
	Route::post( '/album-setting/musicbrainz/search', array( 'as' => 'album-setting.musicbrainz.search', 'uses' => 'AlbumController@search_musicbrainz' ) );
	Route::post( '/album-setting/discogs/search', array( 'as' => 'album-setting.discogs.search', 'uses' => 'AlbumController@search_discogs' ) );
	Route::resource('album-setting', 'AlbumMetaController');

	// AlbumMusicbrainz
	Route::post( '/album-musicbrainz/search', array( 'as' => 'album-musicbrainz.search', 'uses' => 'AlbumMusicbrainzController@index' ) );
	Route::resource( 'album-musicbrainz', 'AlbumMusicbrainzController' );

	// AlbumDiscogs
	Route::post( '/album-discogs/search', array( 'as' => 'album-discogs.search', 'uses' => 'AlbumDiscogsController@index' ) );
	Route::resource( 'album-discogs', 'AlbumDiscogsController' );

	// Release
	Route::model('release', 'Release');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::resource('release', 'ReleaseController');

	// ReleaseMeta
	Route::model('release-meta', 'ReleaseMeta');
	Route::get( '/release-setting/amazon/{release}/lookup', array( 'as' => 'release-setting.amazon.lookup', 'uses' => 'ReleaseMetaController@lookup_amazon' ) );
	Route::get( '/release-setting/itunes/{release}/lookup', array( 'as' => 'release-setting.itunes.lookup', 'uses' => 'ReleaseMetaController@lookup_itunes' ) );
	Route::get( '/release-setting/musicbrainz/{release}/lookup', array( 'as' => 'release-setting.musicbrainz.lookup', 'uses' => 'ReleaseMetaController@lookup_musicbrainz' ) );
	Route::get( '/release-setting/discogs/{release}/lookup', array( 'as' => 'release-setting.discogs.lookup', 'uses' => 'ReleaseMetaController@lookup_discogs' ) );
	Route::post( '/release-setting/amazon/search', array( 'as' => 'release-setting.amazon.search', 'uses' => 'ReleaseMetaController@search_amazon' ) );
	Route::post( '/release-setting/itunes/search', array( 'as' => 'release-setting.itunes.search', 'uses' => 'ReleaseMetaController@search_itunes' ) );
	Route::post( '/release-setting/musicbrainz/search', array( 'as' => 'release.musicbrainz.search', 'uses' => 'ReleaseMetaController@search_musicbrainz' ) );
	Route::post( '/release-setting/discogs/search', array( 'as' => 'release.discogs.search', 'uses' => 'ReleaseMetaController@search_discogs' ) );
	Route::resource('release-setting', 'ReleaseMetaController');

	// Tracks
	Route::model('track', 'Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'before' => 'csrf', 'uses' => 'TrackController@save_order' ) );
	Route::get( '/track/amazon/{release}/lookup', array( 'as' => 'track.amazon.lookup', 'uses' => 'TrackController@lookup_amazon' ) );
	Route::get( '/track/itunes/{release}/lookup', array( 'as' => 'track.itunes.lookup', 'uses' => 'TrackController@lookup_itunes' ) );
	Route::get( '/track/musicbrainz/{release}/lookup', array( 'as' => 'track.musicbrainz.lookup', 'uses' => 'TrackController@lookup_musicbrainz' ) );
	Route::get( '/track/discogs/{release}/lookup', array( 'as' => 'track.discogs.lookup', 'uses' => 'TrackController@lookup_amazon' ) );
	Route::post( '/track/amazon/search', array( 'as' => 'track.amazon.search', 'uses' => 'TrackController@search_musicbrainz' ) );
	Route::post( '/track/itunes/search', array( 'as' => 'track.itunes.search', 'uses' => 'TrackController@search_itunes' ) );
	Route::post( '/track/musicbrainz/search', array( 'as' => 'track.musicbrainz.search', 'uses' => 'TrackController@search_musicbrainz' ) );
	Route::post( '/track/discogs/search', array( 'as' => 'track.discogs.search', 'uses' => 'TrackController@search_discogs' ) );
	Route::resource('track', 'TrackController');

	// TrackMeta
	Route::model('track-meta', 'TrackMeta');
	Route::resource('track-setting', 'TrackMetaController');
});



// Authentication
Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

app/models/Artist.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 4:00 PM
 */

class Artist extends Eloquent {

	protected $table = 'mw_artists';
	protected $primaryKey = 'artist_id';
	protected $softDelete = true;
	protected $fillable = array(
		'artist_last_name',
		'artist_first_name',
		'artist_display_name',
		'artist_settings_mask',
		'artist_navigation_mask',
		'artist_biography',
		'artist_biography_more',
		'artist_bio_last_updated',
	);
	protected $guarded = array(
		'artist_id',
	);

	public function albums() {
		return $this->hasMany('Album', 'album_artist_id', 'artist_id')->orderBy('album_release_date');
	}

	public function meta() {
		return $this->hasMany('ArtistMeta', 'meta_artist_id', 'artist_id');
	}

	public function personnel() {
		return $this->hasMany('Personnel', 'member_parent_id', 'artist_id');
	}

	public function getArtistDisplayNameAttribute() {
		if (empty($this->attributes['artist_display_name'])) {
			if (empty($this->attributes['artist_first_name'])) {
				return !empty($this->attributes['artist_last_name']) ? $this->attributes['artist_last_name'] : null;
			} else {
				return ($this->meta->is_asian_name === true) ?
					$this->attributes['artist_last_name'] . ' ' . $this->attributes['artist_first_name'] :
					$this->attributes['artist_first_name'] . ' ' . $this->attributes['artist_last_name'];
			}
		} else {
			return !empty($this->attributes['artist_display_name']) ? $this->attributes['artist_display_name'] : null;
		}
	}

	public function getAllByInitialLetter() {
		$artist_list = DB::table($this->table)->select(DB::raw('Upper(Substring(artist_last_name From 1 For 1)) as nav'))->groupBy('nav')->orderBy('nav')->get();
		return $artist_list;
	}
}

app/controllers/ArtistController.php
<?php

class ArtistController extends \BaseController {

	private $layout_variables = array();

	public function __construct() {
		global $config_url_base;

		$this->layout_variables = array(
			'config_url_base' => $config_url_base,
		);

		$this->beforeFilter('csrf', array( 'only' => array( 'store', 'update', 'destroy' ) ) );
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$filter = Input::get('browse');

		if (!empty($filter)) {
			$artists = Artist::orderBy('artist_last_name')->where('artist_last_name', 'LIKE', $filter . '%')->get();
		} else {
			$artists = Artist::orderBy('artist_last_name')->get();
		}

		$artist_model = new Artist;
		$artist_list = $artist_model->getAllByInitialLetter();

		$method_variables = array(
			'artists' => $artists,
			'artist_list' => $artist_list,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('artist.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$artist = new Artist;

		$method_variables = array(
			'artist' => $artist,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('artist.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$artist = new Artist;

		$fields = $artist->getFillable();

		foreach ($fields as $field) {
			$artist->{$field} = Input::get($field);
		}

		$result = $artist->save();

		if ($result !== false) {
			return Redirect::route('artist.show', array('id' => $artist->artist_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('artist.index')->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$id->albums->sortByDesc(function ($album) {
			return $album->album_release_date;
		});

		$method_variables = array(
			'artist' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('artist.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$method_variables = array(
			'artist' => $id->load('meta'),
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('artist.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{

		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('artist.show', array('id' => $id->artist_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('artist.index')->with('error', 'Your changes were not saved.');
		}
	}

	/**
	 * Show the form for deleting the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function delete($id) {

		$method_variables = array(
			'artist' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('artist.delete', $data);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Input::get('confirm');
		$artist_display_name = $id->artist_display_name;

		if ($confirm === true) {
			// Gather albums, releases, tracks, audio, and ecommerce.
			if (count($id->albums) > 0) {
				foreach ($id->albums as $album) {
					if (count($album->releases) > 0) {
						foreach ($album->releases as $release) {
							if (count($release->tracks) > 0) {
								foreach ($release->tracks as $track) {
									// Remove track settings
									$track->meta()->delete();

									// Remove ecommerce and content by tracks.
									//$track->ecommerce()->delete();
								}

								// Remove release meta
								$release->meta()->delete();

								// Remove tracks.
								$release->tracks()->delete();


								// Remove ecommerce.
								//$release->ecommerce()->delete();
							}
						}
					}

					// Remove releases.
					$album->releases()->delete();

					// Remove album settings.
					$album->meta()->delete();
				}
			}

			// Remove albums.
			$id->albums()->delete();

			// Remove artist settings.
			$id->meta()->delete();

			// Remove personnel.
			$id->personnel()->delete();

			// Remove artist.
			$artist_id = $id->artist_id;
			$id->delete();

			return Redirect::route('artist.index')->with('message', $artist_display_name . ' was deleted.');
		} else {
			return Redirect::route('artist.show', array('id' => $id->artist_id))->with('error', $artist_display_name . ' was not deleted.');
		}
	}


}

app/views/artist/meta/_form.blade.php
@extends('layout')

@section('content')
<div class="form-group">
	{{ Form::label( 'is_asian_name', 'Use Asian name format:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'is_asian_name', 1, ($artist->meta->is_asian_name == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'is_asian_name', 0, ($artist->meta->is_asian_name == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'is_je_artist', 'J~E artist:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'is_je_artist', 1, ($artist->meta->is_je_artist == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'is_je_artist', 0, ($artist->meta->is_je_artist == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'is_classical_artist', 'Classical artist:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'is_classical_artist', 1, ($artist->meta->is_classical_artist == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'is_classical_artist', 0, ($artist->meta->is_classical_artist == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<h4>Navigation display</h4>

<div class="form-group">
	{{ Form::label( 'nav_profile', 'Profile:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_profile', 1, ($artist->meta->nav_profile == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_profile', 0, ($artist->meta->nav_profile == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'nav_discography', 'Discography:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_discography', 1, ($artist->meta->nav_discography == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_discography', 0, ($artist->meta->nav_discography == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'nav_posts', 'Posts:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_posts', 1, ($artist->meta->nav_posts == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_posts', 0, ($artist->meta->nav_posts == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'nav_shop', 'Shop:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_shop', 1, ($artist->meta->nav_shop == 1) ) }} Yes
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio( 'nav_shop', 0, ($artist->meta->nav_shop == 0) ) }} No
			</label>
		</div>
	</div>
</div>

<h4>Ecommerce and external services</h4>

<div class="form-group">
	{{ Form::label( 'default_amazon_locale', 'Default Amazon locale:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		{{ Form::select( 'default_amazon_locale', Config::get('amazon.locales'), $artist->meta->default_amazon_locale, array( 'class' => 'form-control' ) ) }}
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'default_itunes_store', 'Default iTunes store:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		{{ Form::select( 'default_itunes_store', Config::get('itunes.locales'), $artist->meta->default_itunes_store, array( 'class' => 'form-control' ) ) }}
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'itunes_id', 'iTunes ID:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-7">
		{{ Form::text( 'itunes_id', $artist->meta->itunes_id, array( 'class' => 'form-control' ) ) }}
	</div>
	<div class="col-sm-2">
		<a href="{{ route( 'artist-itunes.index', array( 'artist' => $artist->artist_id ) ) }}" class="btn btn-default btn-sm">Look up</a>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'discogs_artist_id', 'Discogs ID:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		{{ Form::text( 'discogs_artist_id', $artist->meta->discogs_artist_id, array( 'class' => 'form-control' ) ) }}
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'musicbrainz_gid', 'Musicbrainz GID:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-7">
		{{ Form::text( 'musicbrainz_gid', $artist->meta->musicbrainz_gid, array( 'class' => 'form-control' ) ) }}
	</div>
	<div class="col-sm-2">
		<a href="{{ route( 'artist-musicbrainz.index', array( 'artist' => $artist->artist_id ) ) }}" class="btn btn-default btn-sm">Look up</a>
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'yesasia_id', 'YesAsia ID:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		{{ Form::text( 'yesasia_id', $artist->meta->yesasia_id, array( 'class' => 'form-control' ) ) }}
	</div>
</div>

<div class="form-group">
	{{ Form::label( 'emusic_cjsku', 'eMusic SKU:', array( 'class' => 'col-sm-3' ) ) }}
	<div class="col-sm-9">
		{{ Form::text( 'emusic_cjsku', $artist->meta->emusic_cjsku, array( 'class' => 'form-control' ) ) }}
	</div>
</div>

<div class="col-sm-offset-3 col-sm-9">
	{{ Form::submit( 'Save', array( 'class' => 'btn btn-default' ) ) }}
</div>
@stop

app/views/artist/meta/edit.blade.php
@extends('artist.meta._form')

@section('page_title')
&raquo; {{ $artist->artist_display_name }}
&raquo; Edit Settings
@stop

@section('section_header')
<h2>{{ $artist->artist_display_name }}</h2>
@stop

@section('section_label')
<h3>Edit Settings</h3>
@stop

@section('content')
<div class="col-md-12">
	{{ Form::model( $artist, array( 'route' => array('artist-setting.update', $artist->artist_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) }}
	@parent
	{{ Form::close() }}
</div>
@stop