app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'auth'), function () {
	Route::get('/', array( 'as' => 'admin.home', 'uses' => 'HomeController@index' ));

	// Artist
	Route::model('artist', 'Artist');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );
	Route::resource('artist', 'ArtistController');

	// ArtistMeta
	Route::model('artist-meta', 'ArtistMeta');
	Route::get( '/artist-setting/musicbrainz/{artist}/lookup', array( 'as' => 'artist-setting.musicbrainz.lookup', 'uses' => 'ArtistMetaController@lookup_musicbrainz' ) );
	Route::get( '/artist-setting/discogs/{artist}/lookup', array( 'as' => 'artist-setting.discogs.lookup', 'uses' => 'ArtistMetaController@lookup_discogs' ) );
	Route::get( '/artist-setting/itunes/{artist}/lookup', array( 'as' => 'artist-setting.itunes.lookup', 'uses' => 'ArtistMetaController@lookup_itunes' ) );
	Route::post( '/artist-setting/discogs/search', array( 'as' => 'artist-setting.discogs.search', 'uses' => 'ArtistMetaController@search_discogs' ) );
	Route::post( '/artist-setting/itunes/{artist}/search', array( 'as' => 'artist-setting.itunes.serach', 'uses' => 'ArtistMetaController@search_itunes' ) );
	Route::resource('artist-setting', 'ArtistMetaController');

	// ArtistMusicbrainz
	Route::post( '/artist-musicbrainz/search', array( 'as' => 'artist-musicbrainz.search', 'uses' => 'ArtistMusicbrainzController@index' ) );
	Route::resource( 'artist-musicbrainz', 'ArtistMusicbrainzController' );

	// ArtistItunes
	Route::post( '/artist-itunes/search', array( 'as' => 'artist-itunes.search', 'uses' => 'ArtistItunesController@index' ) );
	Route::resource( 'artist-itunes', 'ArtistItunesController' );

	// ArtistItunes
	Route::post( '/artist-discogs/search', array( 'as' => 'artist-discogs.search', 'uses' => 'ArtistDiscogsController@index' ) );
	Route::resource( 'artist-discogs', 'ArtistDiscogsController' );

	// AmazonSearch
	Route::post( '/amazon/search', array( 'as' => 'amazon.search', 'uses' => 'AmazonSearchController@index' ) );
	Route::resource( 'amazon', 'AmazonSearchController' );

	// Personnel
	Route::model('personnel', 'Personnel');
	Route::get( '/personnel/{personnel}/delete', array( 'as' => 'personnel.delete', 'uses' => 'PersonnelController@delete' ) );
	Route::post( '/personnel/save-order', array( 'as' => 'personnel.save-order', 'before' => 'csrf', 'uses' => 'PersonnelController@save_order' ) );
	Route::resource('personnel', 'PersonnelController');

	// Album
	Route::model('album', 'Album');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::resource('album', 'AlbumController');

	// AlbumMeta
	Route::model('album-meta', 'AlbumMeta');
	Route::get( '/album-setting/musicbrainz/{album}/lookup', array( 'as' => 'album-setting.musicbrainz.lookup', 'uses' => 'AlbumController@lookup_musicbrainz' ) );
	Route::get( '/album-setting/discogs/{album}/lookup', array( 'as' => 'album-setting.discogs.lookup', 'uses' => 'AlbumController@lookup_discogs' ) );
	Route::post( '/album-setting/musicbrainz/search', array( 'as' => 'album-setting.musicbrainz.search', 'uses' => 'AlbumController@search_musicbrainz' ) );
	Route::post( '/album-setting/discogs/search', array( 'as' => 'album-setting.discogs.search', 'uses' => 'AlbumController@search_discogs' ) );
	Route::resource('album-setting', 'AlbumMetaController');

	// AlbumMusicbrainz
	Route::post( '/album-musicbrainz/search', array( 'as' => 'album-musicbrainz.search', 'uses' => 'AlbumMusicbrainzController@index' ) );
	Route::resource( 'album-musicbrainz', 'AlbumMusicbrainzController' );

	// AlbumDiscogs
	Route::post( '/album-discogs/search', array( 'as' => 'album-discogs.search', 'uses' => 'AlbumDiscogsController@index' ) );
	Route::resource( 'album-discogs', 'AlbumDiscogsController' );

	// Release
	Route::model('release', 'Release');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::resource('release', 'ReleaseController');

	// ReleaseMeta
	Route::model('release-meta', 'ReleaseMeta');
	Route::get( '/release-setting/amazon/{release}/lookup', array( 'as' => 'release-setting.amazon.lookup', 'uses' => 'ReleaseMetaController@lookup_amazon' ) );
	Route::get( '/release-setting/itunes/{release}/lookup', array( 'as' => 'release-setting.itunes.lookup', 'uses' => 'ReleaseMetaController@lookup_itunes' ) );
	Route::get( '/release-setting/musicbrainz/{release}/lookup', array( 'as' => 'release-setting.musicbrainz.lookup', 'uses' => 'ReleaseMetaController@lookup_musicbrainz' ) );
	Route::get( '/release-setting/discogs/{release}/lookup', array( 'as' => 'release-setting.discogs.lookup', 'uses' => 'ReleaseMetaController@lookup_discogs' ) );
	Route::post( '/release-setting/amazon/search', array( 'as' => 'release-setting.amazon.search', 'uses' => 'ReleaseMetaController@search_amazon' ) );
	Route::post( '/release-setting/itunes/search', array( 'as' => 'release-setting.itunes.search', 'uses' => 'ReleaseMetaController@search_itunes' ) );
	Route::post( '/release-setting/musicbrainz/search', array( 'as' => 'release.musicbrainz.search', 'uses' => 'ReleaseMetaController@search_musicbrainz' ) );
	Route::post( '/release-setting/discogs/search', array( 'as' => 'release.discogs.search', 'uses' => 'ReleaseMetaController@search_discogs' ) );
	Route::resource('release-setting', 'ReleaseMetaController');

	// Tracks
	Route::model('track', 'Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'before' => 'csrf', 'uses' => 'TrackController@save_order' ) );
	Route::get( '/track/amazon/{release}/lookup', array( 'as' => 'track.amazon.lookup', 'uses' => 'TrackController@lookup_amazon' ) );
	Route::get( '/track/itunes/{release}/lookup', array( 'as' => 'track.itunes.lookup', 'uses' => 'TrackController@lookup_itunes' ) );
	Route::get( '/track/musicbrainz/{release}/lookup', array( 'as' => 'track.musicbrainz.lookup', 'uses' => 'TrackController@lookup_musicbrainz' ) );
	Route::get( '/track/discogs/{release}/lookup', array( 'as' => 'track.discogs.lookup', 'uses' => 'TrackController@lookup_amazon' ) );
	Route::post( '/track/amazon/search', array( 'as' => 'track.amazon.search', 'uses' => 'TrackController@search_musicbrainz' ) );
	Route::post( '/track/itunes/search', array( 'as' => 'track.itunes.search', 'uses' => 'TrackController@search_itunes' ) );
	Route::post( '/track/musicbrainz/search', array( 'as' => 'track.musicbrainz.search', 'uses' => 'TrackController@search_musicbrainz' ) );
	Route::post( '/track/discogs/search', array( 'as' => 'track.discogs.search', 'uses' => 'TrackController@search_discogs' ) );
	Route::resource('track', 'TrackController');

	// TrackMeta
	Route::model('track-meta', 'TrackMeta');
	Route::resource('track-setting', 'TrackMetaController');
});



// Authentication
Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

app/models/Release.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 5:31 PM
 */

class Release extends Eloquent {

	protected $table = 'mw_albums_releases';
	protected $primaryKey = 'release_id';
	protected $softDelete = true;
	protected $fillable = array(
		'release_album_id',
		'release_ean_num',
		'release_catalog_num',
		'release_format_id',
		'release_alt_title',
		'release_country_name',
		'release_label',
		'release_release_date',
		'release_image',
	);
	protected $guarded = array(
		'release_id',
		'release_date_modified',
		'release_deleted',
	);

	public function album() {
		return $this->belongsTo('Album', 'release_album_id', 'album_id');
	}

	public function tracks() {
		return $this->hasMany('Track', 'track_release_id', 'release_id');
	}

	public function format() {
		return $this->hasOne('ReleaseFormat', 'format_id', 'release_format_id');
	}

	public function meta() {
		return $this->hasMany('ReleaseMeta', 'meta_release_id', 'release_id');
	}

}

app/controllers/ReleaseController.php
<?php

class ReleaseController extends \BaseController {

	private $layout_variables = array();

	public function __construct() {
		global $config_url_base;

		$this->layout_variables = array(
			'config_url_base' => $config_url_base,
		);

		$this->beforeFilter('auth');

		$this->beforeFilter('csrf', array( 'only' => array( 'store', 'update', 'destroy' ) ) );
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$album_id = Input::get('album');
		if (!empty($album_id)) {
			$releases = Release::where('release_album_id', $album_id)->orderBy('release_catalog_num')->get();
		} else {
			$releases = Release::orderBy('release_catalog_num')->get();
		}
		$releases->load('album');

		$method_variables = array(
			'releases' => $releases,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{

		$release = new Release;
		$release->release_release_date = date('Y-m-d');

		$album_id = Input::get('album');

		if (!empty($album_id)) {
			$release->release_album_id = $album_id;
			$release->album = Album::find($album_id);
			$albums = Album::where('album_artist_id', $release->album->album_artist_id)->orderBy('album_title')->lists('album_title', 'album_id');
		} else {
			$albums = Album::orderBy('album_title')->lists('album_title', 'album_id');
		}
		$albums = array('0' => '&nbsp;') + $albums;

		$formats = ReleaseFormat::all()->lists('format_alias', 'format_id');
		$formats = array('0' => '&nbsp;') + $formats;

		$countries = Country::orderBy('country_name')->lists('country_name', 'country_name');
		$countries = array('0' => '&nbsp;') + $countries;


		$method_variables = array(
			'release' => $release,
			'albums' => $albums,
			'formats' => $formats,
			'countries' => $countries,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$release = new Release;

		$fields = $release->getFillable();

		foreach ($fields as $field) {
			$release->{$field} = Input::get($field);
		}

		$result = $release->save();

		if ($result !== false) {
			return Redirect::route('release.show', array('id' => $release->release_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('album.show', array('id' => $release->release_album_id) )->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$track_model = new Track();
		$id->release_track_list = $track_model->findReleaseTracks($id->release_id);
		//$id->ecommerce->sortBy('ecommerce_list_order');

		$method_variables = array(
			'release' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$albums = Album::where('album_artist_id', $id->album->album_artist_id)->orderBy('album_title')->lists('album_title', 'album_id');
		$albums = array('0' => '&nbsp;') + $albums;

		$formats = ReleaseFormat::lists('format_alias', 'format_id');
		$formats = array('0' => '&nbsp;') + $formats;

		$countries = Country::orderBy('country_name')->lists('country_name', 'country_name');
		$countries = array('0' => '&nbsp;') + $countries;

		$method_variables = array(
			'release' => $id,
			'albums' => $albums,
			'formats' => $formats,
			'countries' => $countries,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('release.show', array('id' => $id->release_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('album.show', array('id' => $id->release_album_id))->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Show the form for deleting the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function delete($id) {

		$method_variables = array(
			'release' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('release.delete', $data);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Input::get('confirm');
		$release_catalog_num = $id->release_catalog_num;
		$album_id = $id->release_album_id;

		if ($confirm === true) {
			/*
			 * Tracks are currently not supported, but this bit of logic will be available if/when they are.
			$ecommerce_tracks = Track::with('ecommerce')->where('track_release_id', $id->release_id)->get();
			foreach ($ecommerce_tracks as $ecommerce_track) {
				$ecommerce_track->ecommerce()->delete();
			}
			 */

			// Remove ecommerce.
			$id->ecommerce()->delete();

			// Remove tracks.
			$id->tracks()->delete();

			// Remove releases.
			$id->delete();
			return Redirect::route('album.show', array('id' => $album_id  ))->with('message', 'The record was deleted.');
		} else {
			return Redirect::route('release.show', array('id' => $id->release_id))->with('error', 'The record was not deleted.');
		}
	}

}

app/views/release/create.blade.php
@extends('release._form')

@section('page_title')
@if (!empty($release->album))
 &raquo; {{ $release->album->artist->artist_display_name }}
 &raquo; {{ $release->album->album_title }}
@endif
 &raquo; Add a release
@stop

@section('section_header')
<hgroup>
	<h2>
		@if (!empty($release->album))
		{{ $release->album->artist->artist_display_name }}
		<small>{{ $release->album->album_title }}</small>
		@else
		Observant Records
		@endif
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Add a release</h3>
@stop

@section('content')
<div class="col-md-12">
	{{ Form::model( $release, array( 'route' => 'release.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) }}
	@parent
	{{ Form::close() }}
</div>
@stop

app/views/release/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $release->album->artist->artist_display_name }}
 &raquo; {{ $release->album->album_title }}
 @if (!empty($release->release_catalog_num)) &raquo; {{ $release->release_catalog_num }} @endif
 &raquo; Delete
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $release->album->artist->artist_display_name }}
		<small>{{ $release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<div class="col-md-12">

</div>
<h3>
	Delete release
	@if (!empty($release->release_catalog_num))
	<small>{{ $release->release_catalog_num }}</small>
	@endif
</h3>
@stop

@section('content')
<div class="col-md-12">
	<p>
		You are about to delete a release @if (!empty($release->release_catalog_num)) <strong>{{ $release->release_catalog_num }}</strong> @endif from the album <em>{{ $release->album->album_title  }}</em>. Deleting a release will also remove all related tracks.
	</p>

	<p>
		Are you sure you want to do this?
	</p>

	{{ Form::model( $release, array( 'route' => array( 'release.destroy', $release->release_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) }}

	<div class="form-group">
		<div class="col-sm-12">
			<div class="radio">
				<label>
					{{ Form::radio('confirm', '1') }} Yes, I want to delete this release.
				</label>
			</div>
			<div class="radio">
				<label>
					{{ Form::radio('confirm', '0') }} No, I don't want to delete this release.
				</label>
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-12">
			{{ Form::submit('Confirm', array( 'class' => 'btn btn-warning' )) }}
		</div>
	</div>

	{{ Form::close() }}

</div>
@stop

app/views/release/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $release->album->artist->artist_display_name }}
 &raquo; {{ $release->album->album_title }}
@if (!empty($release->release_catalog_num))
 &raquo; {{ $release->release_catalog_num }}
@endif
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $release->album->artist->artist_display_name }}
		<small>{{ $release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Release info
	@if (!empty($release->release_catalog_num))
	<small>{{ $release->release_catalog_num }}</small>
	@endif
</h3>
@stop

@section('content')
<div class="col-md-12">

	<ul class="list-inline">
		<li><a href="{{ route( 'release.edit', array( 'id' => $release->release_id ) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
		<li><a href="{{ route( 'release.delete', array( 'id' => $release->release_id ) ) }}" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span> Delete</a></li>
	</ul>

	<ul class="list-unstyled">
		<li class="row">
				<label class="col-md-3">Format</label>
			<div class="col-md-9">
				{{ $release->format->format_name }}
			</div>
		</li>
		@if (!empty($release->release_label))
		<li class="row">
			<label class="col-md-3">Label</label>
			<div class="col-md-9">
				{{ $release->release_label }}
			</div>
		</li>
		@endif
		@if (!empty($release->release_alternate_title))
		<li class="row">
			<label class="col-md-3">Alternate title</label>
			<div class="col-md-9">
				{{ $release->release_alternate_title }}
			</div>
		</li>
		@endif
		@if (!empty($release->release_ean_num))
		<li class="row">
			<label class="col-md-3">UPC No.</label>
			<div class="col-md-9">
				{{ $release->release_ean_num }}
			</div>
		</li>
		@endif
		@if (!empty($release->release_catalog_num))
		<li class="row">
			<label class="col-md-3">Catalog No.</label>
			<div class="col-md-9">
				{{ $release->release_catalog_num }}
			</div>
		</li>
		@endif
		@if (!empty($release->release_release_date))
		<li class="row">
			<label class="col-md-3">Release Date</label>
			<div class="col-md-9">
				{{ date('Y-m-d', strtotime($release->release_release_date)) }}
			</div>
		</li>
		@endif
		@if (!empty($release->release_country_name))
		<li class="row">
			<label class="col-md-3">Country</label>
			<div class="col-md-9">
				{{ $release->release_country_name }}
			</div>
		</li>
		@endif
		@if (!empty($release->release_image))
		<li class="row">
			<label class="col-md-3">Image</label>
			<div class="col-md-9">
				{{ $release->release_image }}
			</div>
		</li>
		@endif
	</ul>

	<h3>Settings</h3>

	<ul class="list-inline">
		<li><a href="{{ route( 'release-setting.edit', array( 'id' => $release->release_id ) ) }}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
	</ul>

	<ul class="list-unstyled">
		<li class="row">
			<label class="col-md-3">Amazon ASIN</label>
			<div class="col-md-9">
				@if ($release->meta->asin_num != null)
				<a href="http://amazon.{{ Config::get('amazon.country_codes')[$release->album->artist->meta->default_amazon_locale] }}/gp/product/{{ $release->meta->asin_num }}">{{ $release->meta->asin_num }}</a>
				@else
				Not set
				<a href="{{ route( 'release-setting.amazon.lookup', array( 'release' => $release->release_id ) ) }}" class="btn btn-default btn-xs">Look up</a>
				@endif
			</div>
		</li>
		<li class="row">
			<label class="col-md-3">Musicbrainz GID</label>
			<div class="col-md-9">
				@if ($release->meta->musicbrainz_gid != null)
				<a href="http://musicbrainz.org/release/{{ $release->meta->musicbrainz_gid }}">{{ $release->meta->musicbrainz_gid }}</a>
				@else
				Not set
				<a href="{{ route( 'release-setting.musicbrainz.lookup', array( 'release' => $release->release_id ) ) }}" class="btn btn-default btn-xs">Look up</a>
				@endif
			</div>
		</li>
		<li class="row">
			<label class="col-md-3">Discogs ID</label>
			<div class="col-md-9">
				@if ($release->meta->discogs_release_id != null)
				<a href="http://discogs.com/release/{{ $release->meta->discogs_release_id }}">{{ $release->meta->discogs_release_id }}</a>
				@else
				Not set
				<a href="{{ route( 'release-setting.discogs.lookup', array( 'release' => $release->release_id ) ) }}" class="btn btn-default btn-xs">Look up</a>
				@endif
			</div>
		</li>
		<li class="row">
			<label class="col-md-3">iTunes ID</label>
			<div class="col-md-9">
				@if ($release->meta->itunes_collection_id != null)
				<a href="http://discogs.com/release/{{ $release->meta->itunes_collection_id }}">{{ $release->meta->itunes_collection_id }}</a>
				@else
				Not set
				<a href="{{ route( 'release-setting.itunes.lookup', array( 'release' => $release->release_id ) ) }}" class="btn btn-default btn-xs">Look up</a>
				@endif
			</div>
		</li>
	</ul>

	<h3>Tracks</h3>

	{{ Form::open( array( 'route' => array( 'track.save-order' ), 'id' => 'save-order-form' ) ) }}
	<ul class="list-inline">
		<li><a href="{{ route( 'track.create', array('release' => $release->release_id) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add a track</a></li>
		@if (count($release->release_track_list) > 0)
		<li>{{ Form::button( 'Save track order', array( 'id' => 'save-order', 'class' => 'btn btn-default' ) ) }}</li>
		@endif
	</ul>
	<p>

	</p>
	{{ Form::close() }}

	@if (count($release->release_track_list) > 0)
	<ol class="list-unstyled disc-list">
		@foreach ($release->release_track_list as $disc_num => $tracks)
		<li> <h4>Disc: <span class="disc-num-display">{{ $disc_num }}</span>:</h4>
			<ol class="list-unstyled track-list">
				@foreach ($tracks as $track)
				<li>
					<div>
						<ul class="list-inline">
							<li><a href="{{ route( 'track.edit', array( 'id' => $track->track_id ) ) }}" title="[Edit]" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span> <span class="sr-only">Edit</span></a></li>
							<li><a href="{{ route( 'track.delete', array( 'id' => $track->track_id ) ) }}" title="[Delete]" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-remove"></span> <span class="sr-only">Delete</span></a></li>
							<li>
								<span class="track-num-display">{{ $track->track_track_num }}</span>. <a href="{{ route( 'track.show', array( 'id' => $track->track_id ) ) }}">{{ $track->track_song_title }}</a>
								<input type="hidden" name="track_id" value="{{ $track->track_id }}" />
								<input type="hidden" name="track_disc_num" value="{{ $track->track_disc_num }}" />
							</li>
						</ul>
					</div>
				</li>
				@endforeach
			</ol>
		</li>
		@endforeach
	</ol>

	<div id="save-order-dialog">
		<p class="msg"></p>
	</div>

	<script type="text/javascript">
		$('.track-list').sortable({
			update: function (event, ui) {
				var new_track_num = 1;
				$(this).children().each(function () {
					$(this).find('.track-num-display').html(new_track_num);
					new_track_num++;
				});
			}
		});
		if ($('.disc-list').children().length > 1) {
			$('.disc-list').sortable({
				update: function (event, ui) {
					var new_disc_num = 1;
					$(this).children().each(function () {
						$(this).find('.disc-num-display').html(new_disc_num);
						$(this).find('.track-list li').each(function () {
							$(this).find('input[name=track_disc_num]').val(new_disc_num);
						});
						new_disc_num++;
					});
				}
			});
		}
		$('#save-order-dialog').dialog({
			autoOpen: false,
			modal: true,
			buttons: {
				"OK": function () {
					$(this).dialog('close');
				}
			}
		});
		$('#save-order').click(function () {
			var tracks = [], track_disc, track_num, track_id, track_info;
			$('.track-list').children().each(function () {
				track_num = $(this).find('.track-num-display').html();
				track_id = $(this).find('input[name=track_id]').val();
				track_disc = $(this).find('input[name=track_disc_num]').val();
				track_info = {
					'track_id': track_id,
					'track_track_num': track_num,
					'track_disc_num': track_disc
				}
				tracks.push(track_info);
			});
			var _token = $('#save-order-form').find('input[name=_token]').val();
			var url = $('#save-order-form').attr('action');
			var data = {
				'tracks': tracks,
				'_token': _token
			};
			$.post(url, data, function (result) {
				$('#save-order-dialog').dialog('open');
				$('#save-order-dialog').find('.msg').html(result);
			}).error(function (result) {
				var error_msg = 'Your request could not be completed. The following error was given: ' + result.statusText;
				$('#save-order-dialog').dialog('open');
				$('#save-order-dialog').find('.msg').html(error_msg);
			});
		});
	</script>

	@else
	<p>
		This release has no tracks.
	</p>
	@endif

</div>

@stop