app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'auth'), function () {
	Route::get('/', array( 'as' => 'admin.home', 'uses' => 'HomeController@index' ));

	// Artist
	Route::model('artist', 'Artist');
	Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );
	Route::resource('artist', 'ArtistController');

	// ArtistMeta
	Route::model('artist-meta', 'ArtistMeta');
	Route::get( '/artist-setting/musicbrainz/{artist}/lookup', array( 'as' => 'artist-setting.musicbrainz.lookup', 'uses' => 'ArtistMetaController@lookup_musicbrainz' ) );
	Route::get( '/artist-setting/discogs/{artist}/lookup', array( 'as' => 'artist-setting.discogs.lookup', 'uses' => 'ArtistMetaController@lookup_discogs' ) );
	Route::get( '/artist-setting/itunes/{artist}/lookup', array( 'as' => 'artist-setting.itunes.lookup', 'uses' => 'ArtistMetaController@lookup_itunes' ) );
	Route::post( '/artist-setting/discogs/search', array( 'as' => 'artist-setting.discogs.search', 'uses' => 'ArtistMetaController@search_discogs' ) );
	Route::post( '/artist-setting/itunes/{artist}/search', array( 'as' => 'artist-setting.itunes.serach', 'uses' => 'ArtistMetaController@search_itunes' ) );
	Route::resource('artist-setting', 'ArtistMetaController');

	// ArtistMusicbrainz
	Route::post( '/artist-musicbrainz/search', array( 'as' => 'artist-musicbrainz.search', 'uses' => 'ArtistMusicbrainzController@index' ) );
	Route::resource( 'artist-musicbrainz', 'ArtistMusicbrainzController' );

	// ArtistItunes
	Route::post( '/artist-itunes/search', array( 'as' => 'artist-itunes.search', 'uses' => 'ArtistItunesController@index' ) );
	Route::resource( 'artist-itunes', 'ArtistItunesController' );

	// ArtistItunes
	Route::post( '/artist-discogs/search', array( 'as' => 'artist-discogs.search', 'uses' => 'ArtistDiscogsController@index' ) );
	Route::resource( 'artist-discogs', 'ArtistDiscogsController' );

	// AmazonSearch
	Route::post( '/amazon/search', array( 'as' => 'amazon.search', 'uses' => 'AmazonSearchController@index' ) );
	Route::resource( 'amazon', 'AmazonSearchController' );

	// Personnel
	Route::model('personnel', 'Personnel');
	Route::get( '/personnel/{personnel}/delete', array( 'as' => 'personnel.delete', 'uses' => 'PersonnelController@delete' ) );
	Route::post( '/personnel/save-order', array( 'as' => 'personnel.save-order', 'before' => 'csrf', 'uses' => 'PersonnelController@save_order' ) );
	Route::resource('personnel', 'PersonnelController');

	// Album
	Route::model('album', 'Album');
	Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
	Route::resource('album', 'AlbumController');

	// AlbumMeta
	Route::model('album-meta', 'AlbumMeta');
	Route::get( '/album-setting/musicbrainz/{album}/lookup', array( 'as' => 'album-setting.musicbrainz.lookup', 'uses' => 'AlbumController@lookup_musicbrainz' ) );
	Route::get( '/album-setting/discogs/{album}/lookup', array( 'as' => 'album-setting.discogs.lookup', 'uses' => 'AlbumController@lookup_discogs' ) );
	Route::post( '/album-setting/musicbrainz/search', array( 'as' => 'album-setting.musicbrainz.search', 'uses' => 'AlbumController@search_musicbrainz' ) );
	Route::post( '/album-setting/discogs/search', array( 'as' => 'album-setting.discogs.search', 'uses' => 'AlbumController@search_discogs' ) );
	Route::resource('album-setting', 'AlbumMetaController');

	// AlbumMusicbrainz
	Route::post( '/album-musicbrainz/search', array( 'as' => 'album-musicbrainz.search', 'uses' => 'AlbumMusicbrainzController@index' ) );
	Route::resource( 'album-musicbrainz', 'AlbumMusicbrainzController' );

	// AlbumDiscogs
	Route::post( '/album-discogs/search', array( 'as' => 'album-discogs.search', 'uses' => 'AlbumDiscogsController@index' ) );
	Route::resource( 'album-discogs', 'AlbumDiscogsController' );

	// Release
	Route::model('release', 'Release');
	Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
	Route::resource('release', 'ReleaseController');

	// ReleaseMeta
	Route::model('release-meta', 'ReleaseMeta');
	Route::get( '/release-setting/amazon/{release}/lookup', array( 'as' => 'release-setting.amazon.lookup', 'uses' => 'ReleaseMetaController@lookup_amazon' ) );
	Route::get( '/release-setting/itunes/{release}/lookup', array( 'as' => 'release-setting.itunes.lookup', 'uses' => 'ReleaseMetaController@lookup_itunes' ) );
	Route::get( '/release-setting/musicbrainz/{release}/lookup', array( 'as' => 'release-setting.musicbrainz.lookup', 'uses' => 'ReleaseMetaController@lookup_musicbrainz' ) );
	Route::get( '/release-setting/discogs/{release}/lookup', array( 'as' => 'release-setting.discogs.lookup', 'uses' => 'ReleaseMetaController@lookup_discogs' ) );
	Route::post( '/release-setting/amazon/search', array( 'as' => 'release-setting.amazon.search', 'uses' => 'ReleaseMetaController@search_amazon' ) );
	Route::post( '/release-setting/itunes/search', array( 'as' => 'release-setting.itunes.search', 'uses' => 'ReleaseMetaController@search_itunes' ) );
	Route::post( '/release-setting/musicbrainz/search', array( 'as' => 'release.musicbrainz.search', 'uses' => 'ReleaseMetaController@search_musicbrainz' ) );
	Route::post( '/release-setting/discogs/search', array( 'as' => 'release.discogs.search', 'uses' => 'ReleaseMetaController@search_discogs' ) );
	Route::resource('release-setting', 'ReleaseMetaController');

	// Tracks
	Route::model('track', 'Track');
	Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
	Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'before' => 'csrf', 'uses' => 'TrackController@save_order' ) );
	Route::get( '/track/amazon/{release}/lookup', array( 'as' => 'track.amazon.lookup', 'uses' => 'TrackController@lookup_amazon' ) );
	Route::get( '/track/itunes/{release}/lookup', array( 'as' => 'track.itunes.lookup', 'uses' => 'TrackController@lookup_itunes' ) );
	Route::get( '/track/musicbrainz/{release}/lookup', array( 'as' => 'track.musicbrainz.lookup', 'uses' => 'TrackController@lookup_musicbrainz' ) );
	Route::get( '/track/discogs/{release}/lookup', array( 'as' => 'track.discogs.lookup', 'uses' => 'TrackController@lookup_amazon' ) );
	Route::post( '/track/amazon/search', array( 'as' => 'track.amazon.search', 'uses' => 'TrackController@search_musicbrainz' ) );
	Route::post( '/track/itunes/search', array( 'as' => 'track.itunes.search', 'uses' => 'TrackController@search_itunes' ) );
	Route::post( '/track/musicbrainz/search', array( 'as' => 'track.musicbrainz.search', 'uses' => 'TrackController@search_musicbrainz' ) );
	Route::post( '/track/discogs/search', array( 'as' => 'track.discogs.search', 'uses' => 'TrackController@search_discogs' ) );
	Route::resource('track', 'TrackController');

	// TrackMeta
	Route::model('track-meta', 'TrackMeta');
	Route::resource('track-setting', 'TrackMetaController');
});



// Authentication
Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

app/models/Track.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 5:38 PM
 */

class Track extends Eloquent {

	protected $table = 'mw_albums_tracks';
	protected $primaryKey = 'track_id';
	protected $softDelete = true;
	protected $fillable = array(
		'track_release_id',
		'track_disc_num',
		'track_track_num',
		'track_song_title',
		'track_sort_title',
		'track_alt_title',
	);
	protected $guarded = array(
		'track_id',
		'track_deleted',
	);

	public function release() {
		return $this->belongsTo('Release', 'track_release_id', 'release_id');
	}

	public function meta() {
		return $this->hasMany('TrackMeta', 'meta_track_id', 'track_id');
	}

	public function findReleaseTracks($release_id) {
		$tracks_formatted = array();
		$tracks = Track::where('track_release_id', $release_id)->orderBy('track_disc_num')->orderBy('track_track_num')->get();

		if (!empty($tracks)) {
			foreach ($tracks as $track) {
				$tracks_formatted[$track->track_disc_num][] = $track;
			}
		}

		return $tracks_formatted;
	}
}

app/controllers/TrackController.php
<?php

class TrackController extends \BaseController {

	private $layout_variables = array();

	public function __construct() {
		global $config_url_base;

		$this->layout_variables = array(
			'config_url_base' => $config_url_base,
		);

		$this->beforeFilter('auth');

		$this->beforeFilter('csrf', array( 'only' => array( 'store', 'update', 'destroy' ) ) );
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$release_id = Input::get('release');

		if (!empty($release_id)) {
			$tracks = Track::where('track_release_id', $release_id)->orderBy('track_disc_num')->orderBy('track_track_num')->get();
		} else {
			$tracks = Track::orderBy('track_release_id')->orderBy('track_disc_num')->orderBy('track_track_num')->get();
		}
		$tracks->load('release', 'song');

		$method_variables = array(
			'tracks' => $tracks,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('track.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$track = new Track;

		$release_id = Input::get('release');

		if (!empty($release_id)) {
			$release = Release::find($release_id);
			$track->release = $release;
			$track->track_release_id = $release->release_id;
			$track->track_album_id = $release->release_album_id;
			$last_disc_num = Track::where('track_release_id', $release_id)->max('track_disc_num');
			if (empty($last_disc_num)) {
				$last_disc_num = 1;
			}

			$track->track_disc_num = $last_disc_num;

			$last_track_num = Track::where('track_release_id', '=', $release_id)->max('track_track_num');
			if (empty($last_track_num)) {
				$last_track_num = 1;
			}

			$track->track_track_num = $last_track_num + 1;

		}


		$songs = $this->build_song_options($track);

		$recordings = $this->build_recording_options($track);

		$releases = $this->build_release_options($track);

		$method_variables = array(
			'track' => $track,
			'songs' => $songs,
			'recordings' => $recordings,
			'releases' => $releases,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('track.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$track = new Track;

		$fields = $track->getFillable();

		foreach ($fields as $field) {
			$track->{$field} = Input::get($field);
		}

		$result = $track->save();

		if ($result !== false) {
			return Redirect::route('track.show', array('id' => $track->track_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('release.show', array('id' => $track->track_release_id))->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$method_variables = array(
			'track' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('track.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$releases = $this->build_release_options($id);

		$artists = Artist::orderBy('artist_last_name')->get()->lists('artist_display_name', 'artist_id');
		$artists = array(0 => '&nbsp;') + $artists;

		$method_variables = array(
			'track' => $id,
			'releases' => $releases,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('track.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Input::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('track.show', array('id' => $id->track_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('release.show', array('id' => $id->track_release_id))->with('error', 'Your changes were not saved.');
		}
	}


	public function delete($id) {

		$method_variables = array(
			'track' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('track.delete', $data);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Input::get('confirm');
		$track_song_title = $id->track_song_title;
		$release_id = $id->track_release_id;

		if ($confirm === true) {
			// Remove ecommerce.
			$id->ecommerce()->delete();

			// Remove track.
			$id->delete();
			return Redirect::route('release.show', array('id' => $id->track_release_id  ))->with('message', $track_song_title . ' was deleted.');
		} else {
			return Redirect::route('track.show', array('id' => $id->track_id))->with('error', $track_song_title . ' was not deleted.');
		}
	}

	public function save_order() {
		$tracks = Input::get('tracks');

		$is_success = true;
		if (count($tracks) > 0) {
			foreach ($tracks as $track) {
				if (false === $this->_update_track($track['track_id'], $track)) {
					$is_success = false;
					$error = 'Track order was not saved. Check disc ' . $track['track_disc_num'] . ', track ' . $track['track_track_num'] . '.';
					break;
				}
			}
		}

		echo ($is_success == true) ? 'Track order has been saved.' : $error;
	}

	private function _update_track($track_id, $input) {
		$track = Track::find($track_id);

		$track->track_disc_num = $input['track_disc_num'];
		$track->track_track_num = $input['track_track_num'];

		return $track->save();
	}

	private function build_release_options($track) {

		if (!empty($track->release->release_album_id)) {
			$release_titles = Release::with('album')->where('release_album_id', $track->release->release_album_id)->orderBy('release_catalog_num')->get();
		} else {
			$release_titles = Release::with('album')->orderBy('release_catalog_num')->get();
		}

		$releases = $release_titles->lists('release_catalog_num', 'release_id');
		foreach ($releases as $r => $release) {
			$releases[$r] = empty($release) ? 'Catalog no. not set' : $release;
			$releases[$r] .= ' (' . $release_titles->find($r)->album->album_title . ')';
		}

		$releases = array(0 => '&nbsp;') + $releases;
		return $releases;
	}

}

app/views/track/_form.blade.php
@extends('layout')

@section('content')

<div class="form-group">

	<div class="form-group">
		{{ Form::label( 'track_release_id', 'Release:', array( 'class' => 'col-sm-2' ) ) }}
		<div class="col-sm-10">
			{{ Form::select( 'track_release_id', $releases, $track->track_release_id, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label( 'track_disc_num', 'Disc no.:', array( 'class' => 'col-sm-2' ) ) }}
		<div class="col-sm-10">
			{{ Form::text( 'track_disc_num', $track->track_disc_num, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label( 'track_track_num', 'Track no.:', array( 'class' => 'col-sm-2' ) ) }}
		<div class="col-sm-10">
			{{ Form::text( 'track_track_num', $track->track_track_num, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label( 'track_song_title', 'Title:', array( 'class' => 'col-sm-2' ) ) }}
		<div class="col-sm-10">
			{{ Form::text( 'track_song_title', $track->track_song_title, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label( 'track_sort_title', 'Sort title:', array( 'class' => 'col-sm-2' ) ) }}
		<div class="col-sm-10">
			{{ Form::text( 'track_sort_title', $track->track_sort_title, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label( 'track_alt_title', 'Alternate title:', array( 'class' => 'col-sm-2' ) ) }}
		<div class="col-sm-10">
			{{ Form::text( 'track_alt_title', $track->track_alt_title, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		{{ Form::label( 'track_va_artist_id', 'Track artist:', array( 'class' => 'col-sm-2', 'id' => 'track-va-artist-label', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'title' => 'For various artists only' ) ) }}
		<div class="col-sm-10">
			{{ Form::select( 'track_va_artist_id', $artists, $track->track_va_artist_id, array( 'class' => 'form-control' ) ) }}
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			{{ Form::submit('Save', array( 'class' => 'button' )) }}
		</div>
	</div>
</div>

<script type="text/javascript">
	(function ($) {
		$('#track-va-artist-label').tooltip();
		$('#track_release_id').chosen();
		$('#track_va_artist_id').chosen();
	})(jQuery);
</script>

@stop

app/views/track/create.blade.php
@extends('track._form')

@section('page_title')
@if (!empty($track->release))
 &raquo; {{ $track->release->album->artist->artist_display_name }}
 &raquo; {{ $track->release->album->album_title }}
@endif
@if (!empty($release->release_catalog_num))
 &raquo; {{ $release->release_catalog_num }}
@endif
 &raquo; Add a track
@stop

@section('section_header')
<hgroup>
	<h2>
		@if (!empty($track->release))
		{{ $track->release->album->artist->artist_display_name }}
		<small>{{ $track->release->album->album_title }}</small>
		@else
		Observant Records
		@endif
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Add a track</h3>
@stop

@section('content')
{{ Form::model( $track, array( 'route' => 'track.store', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post' ) ) }}
@parent
{{ Form::close() }}
@stop

@section('sidebar')
@if (!empty($track->release))
<p>
	<img src="{{ OBSERVANTRECORDS_CDN_BASE_URI }}/artists/{{ $track->release->album->artist->artist_alias }}/albums/{{ $track->release->album->album_alias }}/{{ strtolower($track->release->release_catalog_num) }}/images/cover_front_medium.jpg" width="230" />
</p>

<ul>
	<li><a href="{{ route('release.show', array( 'id' => $track->release->release_id )) }}/">Back to <em>{{ $track->release->album->album_title }}</em> @if (!empty($track->release->release_catalog_num)) ({{ $track->release->release_catalog_num }}) @else (TBD) @endif </a></li>
</ul>
@endif
@stop

app/views/track/delete.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $track->release->album->artist->artist_display_name }}
 &raquo; {{ $track->release->album->album_title }}
@if (!empty($release->release_catalog_num)) &raquo; {{ $release->release_catalog_num }} @endif
 &raquo; {{ $track->track_song_title }}
 &raquo; Delete
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $track->release->album->artist->artist_display_name }}
		<small>{{ $track->release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Delete
	<small>{{ $track->track_song_title }}</small>
</h3>
@stop

@section('content')

<p>
	You are about to delete <strong>{{ $track->track_song_title }}</strong> from the database.
</p>

<p>
	Are you sure you want to do this?
</p>

{{ Form::model( $track, array( 'route' => array( 'track.destroy', $track->track_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'delete' ) ) }}

<div class="form-group">
	<div class="col-sm-12">
		<div class="radio">
			<label>
				{{ Form::radio('confirm', '1') }} Yes, I want to delete {{ $track->track_song_title }}.
			</label>
		</div>
		<div class="radio">
			<label>
				{{ Form::radio('confirm', '0') }} No, I don't want to delete {{ $track->track_song_title }}.
			</label>
		</div>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-12">
		{{ Form::submit('Confirm', array( 'class' => 'button' )) }}
	</div>
</div>

{{ Form::close() }}

@stop

app/views/track/edit.blade.php
@extends('track._form')

@section('page_title')
 &raquo; {{ $track->release->album->artist->artist_display_name }}
 &raquo; {{ $track->release->album->album_title }}
@if (!empty($release->release_catalog_num)) &raquo; {{ $release->release_catalog_num }} @endif
 &raquo; {{ $track->track_song_title }}
 &raquo; Edit
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $track->release->album->artist->artist_display_name }}
		<small>{{ $track->release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Edit
	<small>{{ $track->track_song_title }}</small>
</h3>
@stop

@section('content')
<div class="col-md-12">
	{{ Form::model( $track, array( 'route' => array('track.update', $track->track_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) }}
	@parent
	{{ Form::close() }}
</div>
@stop

app/views/track/index.blade.php
@extends('layout')

@section('page_title')
 &raquo; Tracks &raquo; Browse
@stop

@section('section_header')
<h2>Observant Records</h2>
@stop

@section('section_label')
<h3>
	Tracks
	<small>Browse</small>
</h3>
@stop

@section('content')

<p>
	<a href="{{ route('track.create') }}" class="button"><span class="glyphicon glyphicon-plus"></span> Add a release</a>
</p>

@if (count($tracks) > 0)
<ol class="track-list">
	@foreach ($tracks as $track)
	<li>
		<div>
			<a href="{{ route( 'track.edit', array( 'id' => $track->track_id ) ) }}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a href="{{ route( 'track.delete', array( 'id' => $track->track_id ) ) }}"><span class="glyphicon glyphicon-remove"></span></a>
			<a href="{{ route( 'track.show', array( 'id' => $track->track_id ) ) }}">{{ $track->song->song_title }}</a>
		</div>
	</li>
	@endforeach
</ol>
@endif

@stop

app/views/track/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $track->release->album->artist->artist_display_name }}
 &raquo; {{ $track->release->album->album_title }}
@if (!empty($release->release_catalog_num)) &raquo; {{ $release->release_catalog_num }} @endif
 &raquo; {{ $track->track_song_title }}
@stop

@section('section_header')
<hgroup>
	<h2>
		{{ $track->release->album->artist->artist_display_name }}
		<small>{{ $track->release->album->album_title }}</small>
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>
	Track info
	<small>{{ $track->track_song_title }}</small>
</h3>
@stop

@section('content')
<div class="col-md-12">
	<ul class="list-inline">
		<li><a href="{{ route( 'track.edit', array( 'id' => $track->track_id ) ) }}" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
		<li><a href="{{ route( 'track.delete', array( 'id' => $track->track_id ) ) }}" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span> Delete</a></li>
	</ul>

	<ul class="list-unstyled">
		<li class="row">
			<label class="col-md-3">Disc no.</label>
			<div class="col-md-9">
				{{ $track->track_disc_num }}
			</div>
		</li>
		<li class="row">
			<label class="col-md-3">Track no.</label>
			<div class="col-md-9">
				{{ $track->track_track_num }}
			</div>
		</li>
		<li class="row">
			<label class="col-md-3">Title</label>
			<div class="col-md-9">
				{{ $track->track_song_title }}
			</div>
		</li>
		@if (!empty($track->track_alt_title))
		<li class="row">
			<label class="col-md-3">Alternate title</label>
			<div class="col-md-9">
				{{ $track->track_alt_title }}
			</div>
		</li>
		@endif
		@if (!empty($track->track_sort_title))
		<li class="row">
			<label class="col-md-3">Sort title</label>
			<div class="col-md-9">
				{{ $track->track_sort_title }}
			</div>
		</li>
		@endif
		@if (!empty($track->track_va_artist_id))
		<li class="row">
			<label class="col-md-3">Track artist</label>
			<div class="col-md-9">
				{{ Artist::find($track->track_va_artist_id)->first()->artist_display_name }}
			</div>
		</li>
		@endif
	</ul>

	<h3>Settings</h3>

	<ul class="list-inline">
		<li><a href="{{ route( 'track-setting.edit', array( 'id' => $track->track_id ) ) }}" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span> Edit</a></li>
	</ul>

	<ul class="list-unstyled">
		<li class="row">
			<label class="col-md-3">iTunes ID</label>
			<div class="col-md-9">
				{{ $track->meta->itunes_id }}
			</div>
		</li>
	</ul>
</div>
@stop